# Site settings
title: LoveVicky
name: Love
email: love@lovevicky.com
description: > # this means to ignore newlines until "baseurl:"
  这个世界是美好的，值得我们为之而奋斗。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lovevicky.com" # the base hostname & protocol for your site

timezone: Asia/Shanghai

# name
highlighter: rouge
permalink: /:categories/:title.html

# sns
author: vicky
twitter_username: micneer
github_username:  micneer

# Pages
gems: [jekyll-paginate]
paginate: 50
paginate_path: "p:num"


# Build settings
markdown: kramdown
kramdown:
  input: GFM
  use_coderay: true
  extensions:
    -autolink
    -footnotes
    -smart
  syntax_highlighter: rouge
  coderay: 
    coderay_line_numbers: nil
